### PR TITLE
fix(utils): Use media.discordapp.net for gif stickers

### LINKED ISSUE #3576: [api-docs] Add callout for sticker gif urls (#6831)
A new commit was made into the api-docs repo: https://github.com/discord/discord-api-docs/commit/0a7d731bad7d49c2e49b0687d2a9ec633efeabc9

This is a bot created issue.

### PR DESCRIPTION
**Pull request by Fleny113**
Use media.discordapp.net for gif stickers, cdn.discordapp.com returns a 404 for gif stickers
Add Gif to StickerFromatTypes as it was missing

Upstream: [discord/discord-api-docs#6831](https://github.com/discord/discord-api-docs/pull/6831)
fixes #3576

### CODE REVIEW

**Review by lts20050703 — DISMISSED** [review]
LGTM! Average Discord being Discord I guess lol

**Review by AwesomeStickz — APPROVED** [review]

File: packages/utils/src/images.ts [hunk 1]
```diff
@@ -354,9 +354,17 @@ export function stickerUrl(
   options?: {
     size?: ImageSize
     format?: ImageFormat
+    type?: StickerFormatTypes
   },
 ): string | undefined {
-  return stickerId ? formatImageUrl(`https://cdn.discordapp.com/stickers/${stickerId}`, options?.size ?? 128, options?.format) : undefined
+  if (!stickerId) return undefined
```
Comment (AwesomeStickz) [inline packages/utils/src/images.ts:360]:
```suggestion
  if (!stickerId) return
```

**Review by AwesomeStickz — CHANGES_REQUESTED** [review]

**Review by AwesomeStickz — APPROVED** [review]

**Review by lts20050703 — APPROVED** [review]
