### PR TITLE
fix(ws/shard): update status update payload

### LINKED ISSUE #526: Better Bot Status Edit Function
Rn you cannot really change the bots status to whatever you would like. (`editBotsStatus`)
I already have a code change cause I wanted to try it out: https://github.com/itohatweb/discordeno/tree/new-status
But as you know me my solution is a breaking change so open for suggestions.

### PR DESCRIPTION
**Pull request by ayntee**
Closes #526 

API parity :roll_eyes:

### CODE REVIEW

File: src/types/discord.ts [hunk 1]
```diff
@@ -363,3 +363,15 @@ export interface InviteDeleteEvent {
   /** the unique invite code */
   code: string;
 }
+
+/** https://discord.com/developers/docs/topics/gateway#update-status-gateway-status-update-structure */
+export interface GatewayStatusUpdatePayload {
+  /** unix time (in milliseconds) of when the client went idle, or null if the client is not idle */
+  since: number | null;
+  /** null, or the user's activities */
+  activities: Activity[] | null;
```
Comment (itohatweb) [inline src/types/discord.ts:372]:
```suggestion
  activities: Pick<ActivityPayload, "name" | "type" | "url">[] | null;
```
Bots are only allowed to use `name`, `type` and `url`. I am not sure if bots are allowed to have multiple activities.

**Review by itohatweb — CHANGES_REQUESTED** [review]

File: src/types/discord.ts [hunk 2]
```diff
@@ -6,6 +6,7 @@ import {
 } from "./guild.ts";
 import { MemberCreatePayload } from "./member.ts";
 import { Activity, Application } from "./message.ts";
+import { ActivityPayload } from "./mod";
```
Comment (ayntee) [inline src/types/discord.ts:9]:
```suggestion
import { ActivityPayload } from "./mod.ts";
```

File: src/util/utils.ts [hunk 3]
```diff
@@ -1,30 +1,33 @@
...
-    type: ActivityType;
-  };
-}
-
-export function editBotsStatus(
-  status: StatusType,
-  name?: string,
-  type = ActivityType.Game,
+export function editBotStatus(
+  data: GatewayStatusUpdatePayload,
```
Comment (Skillz4Killz) [inline src/util/utils.ts:18]: why force a dev to pass in since/afk if they never get used?

**Review by Skillz4Killz — APPROVED** [review]

**Review by Skillz4Killz — APPROVED** [review]

**Review by itohatweb — APPROVED** [review]
