### PR TITLE
fix: return types [] => Collection

### LINKED ISSUE #670: Most Functions should not return Arrays
Many functions are returning Arrays. On Discord we have discussed that we should change the returns to Collections.
If you know any function which returns an array pls write a comment.

- [x] getChannelWebhooks
- [x] getMessages
- [x] getPins
- [ ] getChannels
- [ ] getEmojis
- [ ] getChannelInvites
- [ ] getInvites
- [ ] getRoles
- [ ] getGuildTemplates
- [ ] getWebhooks
- [ ] getChannelWebhooks

(getAuditLogs?)

### PR DESCRIPTION
**Pull request by Skillz4Killz**
Closes #670

### CODE REVIEW

File: src/helpers/channels/get_channel_webhooks.ts [hunk 1]
```diff
@@ -1,16 +1,22 @@
...
 /** Gets the webhooks for this channel. Requires MANAGE_WEBHOOKS */
 export async function getChannelWebhooks(channelId: string) {
   await requireBotChannelPermissions(channelId, ["MANAGE_WEBHOOKS"]);
 
-  const result = await rest.runMethod(
+  const result = (await rest.runMethod(
     "get",
     endpoints.CHANNEL_WEBHOOKS(channelId),
-  );
+  )) as DiscordWebhook[];
```
Comment (itohatweb) [inline src/helpers/channels/get_channel_webhooks.ts:15]:
```suggestion
  );
```

File: src/helpers/channels/get_channel_webhooks.ts [hunk 2]
```diff
@@ -1,16 +1,22 @@
...
 import { endpoints } from "../../util/constants.ts";
 import { requireBotChannelPermissions } from "../../util/permissions.ts";
+import { snakeKeysToCamelCase } from "../../util/utils.ts";
 
 /** Gets the webhooks for this channel. Requires MANAGE_WEBHOOKS */
 export async function getChannelWebhooks(channelId: string) {
   await requireBotChannelPermissions(channelId, ["MANAGE_WEBHOOKS"]);
 
-  const result = await rest.runMethod(
+  const result = (await rest.runMethod(
```
Comment (itohatweb) [inline src/helpers/channels/get_channel_webhooks.ts:12]:
```suggestion
  const result = await rest.runMethod<DiscordWebhook[]>(
```

File: src/helpers/channels/get_channel_webhooks.ts [hunk 3]
```diff
@@ -1,16 +1,22 @@
...
     "get",
     endpoints.CHANNEL_WEBHOOKS(channelId),
-  );
+  )) as DiscordWebhook[];
 
-  return result as DiscordWebhook[];
+  return new Collection(
+    result
+      .map((webhook) => snakeKeysToCamelCase<Webhook>(webhook))
+      .map((webhook) => [webhook.id, webhook]),
```
Comment (itohatweb) [inline src/helpers/channels/get_channel_webhooks.ts:20]:
```suggestion
      .map((webhook) => [webhook.id, snakeKeysToCamelCase<Webhook>(webhook)]),
```

File: src/helpers/channels/get_channels.ts [hunk 4]
```diff
@@ -12,21 +13,27 @@ export async function getChannels(guildId: string, addToCache = true) {
   const result = (await rest.runMethod(
     "get",
     endpoints.GUILD_CHANNELS(guildId),
-  ) as DiscordChannel[]);
+  )) as DiscordChannel[];
```
Comment (itohatweb) [inline src/helpers/channels/get_channels.ts:16]: use 
```ts
runMethod<DiscordChannel[]>

File: src/helpers/channels/get_channels.ts [hunk 5]
```diff
@@ -12,21 +13,27 @@ export async function getChannels(guildId: string, addToCache = true) {
...
-      guildId,
-    );
-    if (addToCache) {
-      await cacheHandlers.set(
-        "channels",
-        discordenoChannel.id,
-        discordenoChannel,
-      );
-    }
+  return new Collection(
```
Comment (itohatweb) [inline src/helpers/channels/get_channels.ts:18]: Maybe assign the `Promise.all()` to a const for better readability

File: src/helpers/invites/get_channel_invites.ts [hunk 6]
```diff
@@ -1,15 +1,22 @@
...
+import { Collection } from "../../util/collection.ts";
 import { endpoints } from "../../util/constants.ts";
 import { requireBotChannelPermissions } from "../../util/permissions.ts";
+import { snakeKeysToCamelCase } from "../../util/utils.ts";
 
 /** Gets the invites for this channel. Requires MANAGE_CHANNEL */
 export async function getChannelInvites(channelId: string) {
   await requireBotChannelPermissions(channelId, ["MANAGE_CHANNELS"]);
 
-  const result = await rest.runMethod(
```
Comment (itohatweb) [inline src/helpers/invites/get_channel_invites.ts:9]: use 
```ts
runMethod<DiscordInvite[]>

File: src/helpers/invites/get_channel_invites.ts [hunk 7]
```diff
@@ -1,15 +1,22 @@
...
     "get",
     endpoints.CHANNEL_INVITES(channelId),
-  );
+  )) as DiscordInvite[];
 
-  return result;
+  return new Collection(
+    result
+      .map((invite) => snakeKeysToCamelCase<Invite>(invite))
+      .map((invite) => [invite.code, invite]),
```
Comment (itohatweb) [inline src/helpers/invites/get_channel_invites.ts:20]:
```suggestion
      .map((invite) => [invite.code, snakeKeysToCamelCase<Invite>(invite)]),
```

File: src/helpers/invites/get_invites.ts [hunk 8]
```diff
@@ -1,12 +1,22 @@
...
 import { endpoints } from "../../util/constants.ts";
 import { requireBotGuildPermissions } from "../../util/permissions.ts";
+import { snakeKeysToCamelCase } from "../../util/utils.ts";
 
 /** Get all the invites for this guild. Requires MANAGE_GUILD permission */
 export async function getInvites(guildId: string) {
   await requireBotGuildPermissions(guildId, ["MANAGE_GUILD"]);
 
-  const result = await rest.runMethod("get", endpoints.GUILD_INVITES(guildId));
+  const result = (await rest.runMethod(
```
Comment (itohatweb) [inline src/helpers/invites/get_invites.ts:12]: use 
```ts
runMethod<DiscordInvite[]>

File: src/helpers/invites/get_invites.ts [hunk 9]
```diff
@@ -1,12 +1,22 @@
...
+    "get",
+    endpoints.GUILD_INVITES(guildId),
+  )) as DiscordInvite[];
 
-  return result;
+  return new Collection(
+    result
+      .map((invite) => snakeKeysToCamelCase<Invite>(invite))
+      .map((invite) => [invite.code, invite]),
```
Comment (itohatweb) [inline src/helpers/invites/get_invites.ts:20]:
```suggestion
      .map((invite) => [invite.code, snakeKeysToCamelCase<Invite>(invite)]),
```

File: src/helpers/roles/get_roles.ts [hunk 10]
```diff
@@ -9,7 +12,14 @@ import { requireBotGuildPermissions } from "../../util/permissions.ts";
 export async function getRoles(guildId: string) {
   await requireBotGuildPermissions(guildId, ["MANAGE_ROLES"]);
 
-  const result = await rest.runMethod("get", endpoints.GUILD_ROLES(guildId));
+  const result = (await rest.runMethod(
```
Comment (itohatweb) [inline src/helpers/roles/get_roles.ts:15]: use 
```ts
runMethod<DiscordRole[]>
```

File: src/helpers/roles/get_roles.ts [hunk 11]
```diff
@@ -9,7 +12,14 @@ import { requireBotGuildPermissions } from "../../util/permissions.ts";
...
+    "get",
+    endpoints.GUILD_ROLES(guildId),
+  )) as DiscordRole[];
 
-  return result;
+  return new Collection(
+    result
+      .map((role) => snakeKeysToCamelCase<Role>(role))
+      .map((role) => [role.id, role]),
```
Comment (itohatweb) [inline src/helpers/roles/get_roles.ts:23]:
```suggestion
      .map((role) => [role.id, snakeKeysToCamelCase<Role>(role)]),
```

File: src/helpers/templates/get_guild_templates.ts [hunk 12]
```diff
@@ -16,5 +17,10 @@ export async function getGuildTemplates(guildId: string) {
     endpoints.GUILD_TEMPLATES(guildId),
   )) as DiscordTemplate[];
 
-  return templates.map((template) => structures.createTemplateStruct(template));
```
Comment (itohatweb) [inline src/helpers/templates/get_guild_templates.ts:19]: Aren't we going to remove templateStruct? Thats why I did not rename it to DiscordenoGuildTemplate in this case.

File: src/helpers/webhooks/get_webhooks.ts [hunk 13]
```diff
@@ -1,12 +1,22 @@
...
 import { endpoints } from "../../util/constants.ts";
 import { requireBotGuildPermissions } from "../../util/permissions.ts";
+import { snakeKeysToCamelCase } from "../../util/utils.ts";
 
 /** Returns a list of guild webhooks objects. Requires the MANAGE_WEBHOOKs permission. */
 export async function getWebhooks(guildId: string) {
   await requireBotGuildPermissions(guildId, ["MANAGE_WEBHOOKS"]);
 
-  const result = await rest.runMethod("get", endpoints.GUILD_WEBHOOKS(guildId));
+  const result = (await rest.runMethod(
```
Comment (itohatweb) [inline src/helpers/webhooks/get_webhooks.ts:12]: use 
```ts
runMethod<DiscordWebhook[]>
```

File: src/helpers/webhooks/get_webhooks.ts [hunk 14]
```diff
@@ -1,12 +1,22 @@
...
+    "get",
+    endpoints.GUILD_WEBHOOKS(guildId),
+  )) as DiscordWebhook[];
 
-  return result;
+  return new Collection(
+    result
+      .map((webhook) => snakeKeysToCamelCase<Webhook>(webhook))
+      .map((webhook) => [webhook.id, webhook]),
```
Comment (itohatweb) [inline src/helpers/webhooks/get_webhooks.ts:20]:
```suggestion
      .map((webhook) => [webhook.id, snakeKeysToCamelCase<Webhook>(webhook)]),
```
