### PR TITLE
fix: remove structure automatic caching

### LINKED ISSUE #464: structures: remove automatic caching
Some structure.create* functions automatically cache the created structure. As discussed all structures should be cached manually after creating.

### PR DESCRIPTION
**Pull request by ayntee**
Closes #464

### CODE REVIEW

File: src/api/controllers/interactions.ts [hunk 1]
```diff
@@ -5,15 +5,22 @@ import {
   InteractionCommandPayload,
 } from "../../types/mod.ts";
 import { structures } from "../structures/mod.ts";
+import { cacheHandlers } from "./cache.ts";
 
 export async function handleInternalInteractionCreate(data: DiscordPayload) {
   if (data.t !== "INTERACTION_CREATE") return;
 
   const payload = data.d as InteractionCommandPayload;
+  const member = await structures.createMember(
```
Comment (ayntee) [inline src/api/controllers/interactions.ts:14]:
```suggestion
  const memberStruct = await structures.createMember(
```

File: src/api/controllers/interactions.ts [hunk 2]
```diff
@@ -5,15 +5,22 @@ import {
...
 
 export async function handleInternalInteractionCreate(data: DiscordPayload) {
   if (data.t !== "INTERACTION_CREATE") return;
 
   const payload = data.d as InteractionCommandPayload;
+  const memberStruct = await structures.createMember(
+    payload.member,
+    payload.guild_id,
+  );
+  await cacheHandlers.set("members", member.id, member);
```
Comment (ayntee) [inline src/api/controllers/interactions.ts:18]:
```suggestion
  await cacheHandlers.set("members", memberStruct.id, memberStruct);
```

File: src/api/controllers/interactions.ts [hunk 3]
```diff
@@ -5,15 +5,22 @@ import {
...
+    payload.member,
+    payload.guild_id,
+  );
+  await cacheHandlers.set("members", memberStruct.id, memberStruct);
+
   eventHandlers.interactionCreate?.(
     {
       ...payload,
-      member: await structures.createMember(payload.member, payload.guild_id),
+      member,
```
Comment (ayntee) [inline src/api/controllers/interactions.ts:23]:
```suggestion
      memberStruct,
```

File: src/api/handlers/guild.ts [hunk 4]
```diff
@@ -620,7 +631,13 @@ export async function getMembers(
     ) as MemberCreatePayload[];
 
     const memberStructures = await Promise.all(
-      result.map((member) => structures.createMember(member, guildID)),
+      result.map(async (memb) => {
+        const memberStruct = await structures.createMember(memb, guildID);
```
Comment (itohatweb) [inline src/api/handlers/guild.ts:635]:
```suggestion
      result.map(async (member) => {
        const memberStruct = await structures.createMember(member, guildID);
```

File: src/api/controllers/misc.ts [hunk 5]
```diff
@@ -53,7 +53,15 @@ export async function handleInternalReady(
         // All the members that came in on guild creates should now be processed 1 by 1
         for (const [guildID, members] of initialMemberLoadQueue.entries()) {
           await Promise.all(
-            members.map((member) => structures.createMember(member, guildID)),
+            members.map(async (memb) => {
+              const memberStruct = await structures.createMember(memb, guildID);
```
Comment (itohatweb) [inline src/api/controllers/misc.ts:57]:
```suggestion
            members.map(async (member) => {
              const memberStruct = await structures.createMember(member, guildID);
```

**Review by itohatweb — CHANGES_REQUESTED** [review]
